---
 - hosts: db
 - name: database assignment
   import_playbook: ../static-assignments/database.yml

#- hosts: nginx
#- name: nginx assignment
#  import_playbook: ../static-assignments/nginx.yml

# - hosts: lb
# - name: Include dynamic variables 
#   import_playbook: ../static-assignments/common.yml 
#   include: ../dynamic-assignments/env-vars.yml
#   tags:
#    - always

# - name: Loadbalancers assignment
#   import_playbook: ../static-assignments/loadbalancers.yml
#   when: load_balancer_is_required

#  - hosts: artifactory
#  - name: artifactory assignment
#    import_playbook: ../static-assignments/artifactory.yml

# - hosts: sonar
# - name: sonar assignment
#   ansible.builtin.import_playbook: ../static-assignments/sonar.yml

# - hosts: todo
# - name: Deploy the todo application
#   ansible.builtin.import_playbook: ../static-assignments/deployment.yml
